### ISSUE TITLE
'retryInBackgroundAfter' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by PetresS** [lucas34/SwiftQueue#100]
I'm using Swift 3.2 with your lib (1.6.0)

`retryInBackgroundAfter` have to be `fileprivate` for me. Hope that I'm not the only one.

**Comment by lucas34** [comment]
Thanks, I'm going to run some tests to make sure the lib is also working properly with swift 4.1 and xcode 9.3.

**Comment by PetresS** [comment]
I would appreciate if you create a tag with this merge 💯 :)

**Comment by lucas34** [comment]
Released under 1.6.1 https://github.com/lucas34/SwiftQueue/releases/tag/1.6.1
With Swift 4.1 compatibility. Please confirm it solves your problem.

**Comment by PetresS** [comment]
it is working now for me ;) 
Thank you 🥇
