### ISSUE TITLE
Question: is there a way to know if the SwiftQueueManager is paused?

### ISSUE THREAD

**Issue by tanis2000** [lucas34/SwiftQueue#144]
I see that I can pause jobs with the `pause()` method but it looks like there is no way to know if the manager is in the `paused` state. Any hint?

**Comment by lucas34** [comment]
Actually no but we can (and we should) add a getter for `isSuspended` in `SwiftQueueManager`

**Comment by tanis2000** [comment]
Ok, if you don't do it sooner than me, I'll send you a PR with that change as it's something I need for the project I'm currently working on. Cheers!

**Comment by lucas34** [comment]
If you can submit a PR that would be the best. I will merge it ASAP.
I also have the version 2 in my backlog. After I merge I'll make the 2.0.0 release.
