### ISSUE TITLE
Suspending a job that has a delay

### ISSUE THREAD

**Issue by tanis2000** [lucas34/SwiftQueue#147]
I stumbled upon a problem I didn't think about before. All my jobs are being run after a delay. I thought I'd be able to suspend them whenever I need to, but it looks like the current implementation is actually creating the `Operation` and in its `run` method it's just waiting the time set by the delay. That way, even if the `OperationQueue` is being suspended, all of the tasks that I queued are already being run and can't be suspended. 

Have you got any idea how I could change this to make operations with delays suspendable?
Cheers!

**Comment by lucas34** [comment]
Hi,
yes you are absolutely correct about the behaviour of `isSuspended` in `OperationQueue`.
I used to implement the behaviour you wanted in early version but I found that some of the jobs was running twice after changing `isSuspended` flag to false. 
However, it should still be possible to add this feature is the future.
