### ISSUE TITLE
Missing CFBundleVersion?

### ISSUE THREAD

**Issue by mylesbarros** [lucas34/SwiftQueue#149]
I'm attempting to build a production version of an app which has SwiftQueue as a dependency. When I do so and attempt to validate it with iTunes Connect I receive an error that...

`SwiftQueue framework is invalid. The Info.plist file is missing the required key: CFBundleVersion`

In the `SwiftQueue.xcodeproj/SwiftQueue_Info.plist` file `CFBundleVersion` is mapped to a build variable called `CURRENT_PROJECT_VERSION`. In the build settings it looks like `CURRENT_PROJECT_VERSION` isn't actually set to anything which I assume isn't deliberate.

Am I misunderstanding or does that need to be added to the source?

**Comment by lucas34** [comment]
I'm using this library in another project and I haven't face this issue. Other libraries like RxSwift and Moya also use this kind of configuration.

If I not mistaken `CURRENT_PROJECT_VERSION` should be set on your side in your project.
Can you try this: https://stackoverflow.com/questions/39673280/how-to-set-current-project-version-in-xcode-8

**Comment by moyoteg** [comment]
I submitted a simple fix in this PR: https://github.com/lucas34/SwiftQueue/pull/153

**Comment by lucas34** [comment]
Merged
