### ISSUE TITLE
SwiftQueue is requires minimum iOS 10.3??

### ISSUE THREAD

**Issue by lokeshvunnam1989** [lucas34/SwiftQueue#15]
When i try to import SwiftQueue using Carthage its asking minimum deployment target should be iOS 10.3. My target was iOS 9.0.

Can some one give some idea what changes i need to do, to support minimum iOS 9.0.

**Comment by lucas34** [comment]
Hi,

I'm not super familiar with carthage. I'm only using the library on a ios 8 target by pod. 

I added some missing configurations.
Please try again with

`
github "lucas34/SwiftQueue" "master"
`

**Comment by lucas34** [comment]
SwiftQueue is now in 1.0.0 version. Can be used with full carthage support
