### ISSUE TITLE
How to be notified that a job cancelation process is finished?

### ISSUE THREAD

**Issue by Narayane** [lucas34/SwiftQueue#152]
All is in my question :) 

In [android-priority-jobqueue](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/JobManager.java#LC245) for example, they give the opportunity to define a callback.

Would it be possible to have something equivalent?

Thanks.

**Comment by lucas34** [comment]
Having a JobCallback is something that we can add but never been implemented yet.
