### ISSUE TITLE
Expose `count` inside `SwiftQueueManager`

### ISSUE THREAD

**Issue by hang321** [lucas34/SwiftQueue#154]
Hi, is it possible to expose the number of jobs in SwiftQueueManager?
```
public func count() -> Int {
  return manage.values.count
}
```

**Comment by lucas34** [comment]
Should be possible but if we do so I suggest we have 2 methods
`queueCount() -> Int` and `jobCount()`.

**Comment by hang321** [comment]
I submitted a pull request #160

**Comment by lucas34** [comment]
Merged
