### ISSUE TITLE
Periodic job stopped running after calling onDone with error

### ISSUE THREAD

**Issue by jelleheemskerk** [lucas34/SwiftQueue#16]
I'm trying to create a periodic job that runs once every **_x_** time. But when `onDone(error: Swift.Error?)` is called with an error it never reschedules.

**Comment by lucas34** [comment]
You have to specify in the builder the number of times you allow this jobs to retry. 
.retry(max: Int)

If you want your job to run "forever" you can specify Int.max as retry count.
In the next version I'll probably update the retry function to allow a full unlimited retry.

**Comment by lucas34** [comment]
In the current implementation, the retry count is not per attempt to run the job. It's global for the job.
We can implement a "retry per attempt" for periodic jobs. So the retry count will be reset to 0 each time the scheduled job runs.

**Comment by jelleheemskerk** [comment]
Thanks for the quick response. If it works as intended you can close this issue.
