### ISSUE TITLE
Cancel all operations with SwiftQueueManager reference

### ISSUE THREAD

**Issue by SureshSc** [lucas34/SwiftQueue#171]
I wanted to cancel all the operations which is scheduled or in execution without the SwiftQueueManager reference.

is there any way?

Scenario: Image is being upload mean while i am logging out from my app, so i wanna cancel all the uploading operations.

**Comment by lucas34** [comment]
You will need to keep the reference to the SwiftQueueManager.  I suggest you either keep it into a singleton so it's available everywhere or at the App level. 
In you case in your logout method you will need to inject the SwiftQueueManager instance.
