### ISSUE TITLE
Facing issue in syncronisation

### ISSUE THREAD

**Issue by Dhillon22** [lucas34/SwiftQueue#188]
Hi,
I am using JobCreator with custom params as below
      let swiftQueueManager =  SwiftQueueManagerBuilder(creator: JobCreator(otherParams : otherParams, completion:completionForJob)).build()

First thing is I run this line of code every time i.e. this instance is created every time as the params values is different always and there is no way to set JobCreator in ManagerBuilder other than  initialisation. 
After 3-4 such runs, the jobs get executed but not in synchronised manner.

Do I need to keep the instance of manager on class level? If yes, then how can I set job creator in the  manager as it has different params every time.

And how is job removed after successful run? Do I manually need to call remove function after execution in onRun() method?

Please respond.
Thanks

**Comment by lucas34** [comment]
Hi,

Yes you do need to keep the reference to `SwiftQueueManagerBuilder `. I suggest you keep it inside a singleton or at the AppDelegate.

Job added should run synchronously. That is the case for the test cases. However if the constraint are not satisfy it won't.

The job is removed automatically based on success or failure condition.

**Comment by lucas34** [comment]
`SwiftQueueManagerBuilder` will manage multiples queues. Each queue can have multiple jobs.

**Comment by Dhillon22** [comment]
I have created properties in JobCreator and in Job class. I am passing values to creator properties while creating Builder instance.
Is this correct way?
If not, How can I create properties in JobCreator class and pass the value to them?

**Comment by lucas34** [comment]
I'm not sure why your JobCreator need parameters. Maybe you can consider passing those parameters to the job itself.

**Comment by Dhillon22** [comment]
I tried by keeping global instance of SwiftQueueManager.
But in that case only first instance of job is getting executed but not any further jobs are getting run.

**Comment by lucas34** [comment]
@Dhillon22 Well do you have any used cased ? Otherwise it's hard to tell what's wrong. 

Maybe some constraints are not satisfied for the second job and it's then blocking the queue. 
Try to add more logs. You can also enable the internal built-in logger that can help you debug
```
SwiftQueueManagerBuilder(creator: MyJobCreator()).set(logger = ConsoleLogger()).build()
```

**Comment by Dhillon22** [comment]
Its still not working for me.
Lemme explain in detail. I am creating notes in offline/online and firing network request through SwiftQueue.



***************************************************************************************************
Step 1: I created instance of builder on class level as follows :

let addNoteManager = SwiftQueueManagerBuilder(creator: AddNotesJobCreator()).set(logger: ConsoleLogger()).build()
***************************************************************************************************
Step 2 : Created JobBuilder as follows

 let jobParams : [String : Any?] = ["param":param!,
                                               "otherParams" : otherParams,
                                               "completion" : completionForJob]
//otherParams is of Type [String:Any?]
//completion is a function


 JobBuilder(type: AddNotesJob.type)
                //Add Group Name
                .group(name: "AddNote")
                // Requires internet to run
                .internet(atLeast: .cellular)
                // params of my job
                .with(params: jobParams)
                // Add to queue manager
                .schedule(manager: addNoteManager)

jobParams include [String : Any] type arguments. I am passing a function also in params as completionHandler for the network request.

***************************************************************************************************
Step 3: Below is my Job Class:

class AddNotesJob :Job {
    
    // Type to know which Job to return in job creator
    static let type = "AddNotesJob"
    // Param
    private let params: [String: Any?]?
    public let completion :  (ResultType) -> Void
    
    public let urlString :  String
    public let headers : [String:String]
    public let entityName :  String
    
    
    
    required init(params: [String: Any]) {
        // Receive params from JobBuilder.with()
        
        self.params = params["param"] as! [String : Any?] //Params for request
        let otherParams : [String : Any?] = params["otherParams"] as! [String : Any?]
        self.urlString = otherParams["urlString"] as! String
        self.headers = otherParams["headers"] as! [String : String]
        self.entityName = otherParams["entityName"] as! String
        
        self.completion = params["completion"] as! (ResultType) -> Void
    }
    
    func onRun(callback: JobResult) {
        let request = WSRequest(urlString: urlString, method: .delete, parameters: params , headers: headers)
        let networking = Network()
        networking.putRequest(request, completion: { (result:ResultType)  in
            self.completion(result)
        })
    }
    
    func onRetry(error: Error) -> RetryConstraint {
        // Check if error is non fatal
        let err = error as NSError
        
        return err.code > 400 ? RetryConstraint.cancel : RetryConstraint.retry(delay: 0) // immediate retry
    }
    
    func onRemove(result: JobCompletion) {
        // This job will never run anymore
        switch result {
        case .success:
            // Job success
            DLog(message: "Completed running of Notes job.")
            break
            
        case .fail(_ ):
            // Job fail
            break
            
        }
    }
}
***************************************************************************************************
Step 4: Below is job creator:

class AddNotesJobCreator: JobCreator {
    
    
    // Base on type, return the actual job implementation
    func create(type: String, params: [String: Any]?) -> Job {
        // check for job and params type
        if type == AddNotesJob.type  {
            return AddNotesJob(params: params!)
        } else {
            // Nothing match
            // You can use `fatalError` or create an empty job to report this issue.
            fatalError("No Job !")
        }
    }
}

***************************************************************************************************



Now if I create a new instance of manager by making below code local, then all the requests are getting executed jus the queue is not maintained.

let addNoteManager = SwiftQueueManagerBuilder(creator: AddNotesJobCreator()).set(logger: ConsoleLogger()).build()


But if i keep above line of code at global level then only first instance of request is getting executed.
For next jobs, onRun method is not getting called although the operation is getting added to queue.
This is all that I have implemented.
Please lemme know if any more info is required

**Comment by lucas34** [comment]
Add callback.done(.success) in onRun method.

```
func onRun(callback: JobResult) {
    let request = ...
    let networking = ...
    networking.putRequest(request, completion: { (result:ResultType)  in
       callback.done(.success) /// This will indicate that the job is completed to the job manager
    })
}
```

**Comment by lucas34** [comment]
Let me know how I can improve the documentation or the ReadMe in order to make this more explicit.
Thanks.

**Comment by Dhillon22** [comment]
Sure I will compile a list and will share with you. I do have some inputs for this.
One more thing, I was trying to persist this job and as you could see I am passing a completionHandler (which is a function) in the params to job class. 

The app crashes on below line in JobBuilder class:
            assert(JSONSerialization.isValidJSONObject(info.params))

As it is not able to serialize a function, so the json is invalid. That is why I was using different parameters in Jobcreator.
So currently I am not able to persist JOB.

**Comment by Dhillon22** [comment]
That means I have to create instance of JobManager every time as there is no other way to pass callback function to JobCreator.
i.e I have to make below line local to function and then pass the params in JobCreator as I was doing initially (see my first comment for reference)
   let addNoteManager = SwiftQueueManagerBuilder(creator: AddNotesJobCreator()).set(logger: ConsoleLogger()).build()

This will again bring me back to where I was initially. So either persist or make serial queue.
So,It does not support both, in case I have a callback to be passed to Job itself.
