### ISSUE TITLE
Cancel all jobs under a specific queue while multiple queues are in progress

### ISSUE THREAD

**Issue by sgpushpaveni** [lucas34/SwiftQueue#19]
Hello Lucas,

I would request your support for the below scenario.

I have set up the download queue as below

Initiated one queue with queueName and tag (q1) which in turn create multiple jobs with the job name and tag name. Tag name(tag_q1) is same for all the jobs under the first queue (q1)

Initiated 2nd queue with queueName and tag (q2) which in turn create multiple jobs with the job name and tag name. Tag name(tag_q2) is same for all the jobs under the 2nd queue (q2)

Both queues are running in parallel, now I have to delete q1 and its jobs with tag name tag_q1.

I tried to cancel the jobs using the "cancelOperations(tag:"tag_q1"), but its not cancelling the job even one single job.

Kindly share your comments on how to this situation with SwiftQueue.

**Comment by lucas34** [comment]
Hi,

By not canceled do you mean "onRemove()" is not called when you cancel the job ?
All jobs will be referenced from the SwiftQueueManager. Are you calling cancel on the same instance ? 

I updated the tests to add the behaviour you mentioned. I'm not able to reproduce.

**Comment by sgpushpaveni** [comment]
Hello Lucas, Thanks for the sample test cases and got your point on the same instance to be used.
