### ISSUE TITLE
Question regarding failed jobs

### ISSUE THREAD

**Issue by astjohn** [lucas34/SwiftQueue#198]
First, thank you for the wonderful library!

Let's say I have a job group like this:

```
JobBuilder(type: CatJob.type)
            .with(params: [CatJob.PARAM_CAT_ID: catId])
            .singleInstance(forId: catId)
            // Requires internet to run
            .internet(atLeast: .cellular)
            //  will run in parallel to other group names, in sequence with other device info
            .group(name: "cats")
            .retry(limit: .limited(10))
            // Add to queue manager
            .schedule(manager: queueManager)
```

and inside the job, we have something like this:

```
func onRetry(error: Error) -> RetryConstraint {
        if let err = error as? SyncError {
            switch (err) {
            case .apiError(let httpStatus):
                if httpStatus == 400 {
                    return RetryConstraint.cancel
                }
            case .localError:
                // do nothing, fall through to below
                break
            }
        }
        return RetryConstraint.exponential(initial: 10) 
    }
```

And now I add 3 cat jobs. The first one succeeds, but the second one fails.

Will the library continue to retry the second cat job before proceeding to cat job #3? From what I can tell, this seems to be the case. Is it possible to configure the library to continue to process all of the cat jobs and simply push the failing ones to the bottom of the queue?

Thanks!

**Comment by lucas34** [comment]
Hi,
First, Thanks for using the library. 

Right now the library is made to have the jobs running in sequence and have to be terminated before running the next job. It's not possible right now to push the job to the bottom of the queue.

However that would be an interesting feature.

**Comment by astjohn** [comment]
This is important for us as for example, we may be syncing a whole bunch of individual cats and we might not want the failure of one to prevent others from being saved to the device. I'll take a look eventually to see if the current architecture might allow for something like this, but you likely know better than myself. Is there any particular place I should start looking at?

**Comment by lucas34** [comment]
If the order does not really matter, using multiple queues in parallel will solve the problem. So you can set a unique `groupId` for each task
