### ISSUE TITLE
Retry

### ISSUE THREAD

**Issue by fdm-jdnora** [lucas34/SwiftQueue#202]
Hi,

I just wanted to ask how to go about executing a job only once.

I tried implementing the onRetry(error: Error) method with a return of RetryConstraint.cancel

Also, I built the job with the retry option set at .limited(0.0) and .limited(-1.0).

By looking at the console when executing queued jobs, it appears that the job's onRun method gets executed twice.

Hope you can help.

Regards,
Dennis

**Comment by lucas34** [comment]
Please check the number of maximum retry you are allowing https://github.com/lucas34/SwiftQueue/blob/master/Sources/SwiftQueue/JobBuilder.swift#L90
