### ISSUE TITLE
Run daily at 4 am

### ISSUE THREAD

**Issue by yamifr07** [lucas34/SwiftQueue#203]
I want to run the job every day between 4 and 5 am. What should I do?

**Comment by lucas34** [comment]
I'm not sure about the feasibility of this feature. We app could have been killed or in background. So how do you want the app to react in those cases ?

**Comment by yamifr07** [comment]
Is there any possibility of running the job anyway?  Like when you kill an app and still receiving notifications. I want to run background tasks.

**Comment by lucas34** [comment]
Seems not possible on iOS by design. App must be running. Feel free to link me any documentation that can help

**Comment by yamifr07** [comment]
So when I set .periodic it won't run nevermore if the app has been killed?

**Comment by lucas34** [comment]
No, this is by design from Apple
