### ISSUE TITLE
Question: How do we get a Job counts that keep and finished currently in SqOperationQueue?

### ISSUE THREAD

**Issue by haptaro** [lucas34/SwiftQueue#214]
I'm thinking about multiple Images uploading service with SwiftQueue.
For example, If I take three photos,  three jobs would insert into queue like `0/3` .
As soon as I insert into queue, the first job will execute like `1/3` .

Then, in order to show the progress of jobs to User, I'd like to know jobs that keep and finished currently in SqOperationQueue.
<img width="422" alt="Screen Shot 2019-05-06 at 4 19 31 PM" src="https://user-images.githubusercontent.com/9423755/57211315-ca7a8b00-701a-11e9-91b4-554c50a71c96.png">

If I get a job counts that keep and finished currently in SqOperationQueue, I can show the progress of jobs to User.
Please tell me🙏

Thank you ahead of time.

**Comment by lucas34** [comment]
Does all your jobs are running the same queue (same group) ?

**Comment by haptaro** [comment]
Yes
Same queue!

**Comment by lucas34** [comment]
This may help https://github.com/lucas34/SwiftQueue/pull/218
