### ISSUE TITLE
Question regarding params serialization

### ISSUE THREAD

**Issue by gumbright** [lucas34/SwiftQueue#222]
As params are specified as [String : Any] is the intent that when serialized params is stored as a string of the dictionary rather than a dictionary?

For example executing:

> JobBuilder(type: MyJob.type)
>   .internet(atLeast: .cellular)
>  .with(params: ["jobNumber": "\(jobNumber)"])  //jobNumber = 0
>  .delay(time:delay) //15
>  .persist(required: true)
>  .retry(limit: .unlimited)
>  .schedule(manager: manager)`

serializes as (pulling this out of console, please excuse the escapes):

`"{\"requireNetwork\":1,\"isPersisted\":true,\"uuid\":\"1A1C0E1B-6B3D-4539-AA4D-5EE734B11E2B\",\"override\":false,\"includeExecutingJob\":true,\"delay\":15,\"interval\":0,\"params\":\"{\\\"jobNumber\\\":\\\"0\\\"}\",\"tags\":[],\"type\":\"MyJob\",\"runCount\":-1,\"createTime\":580271177.77153206,\"group\":\"GLOBAL\",\"retries\":{\"value\":-1},\"requireCharging\":false,\"maxRun\":{\"value\":0},\"deadline\":null}"`

Note that params is serializing as a string of JSON rather than a structure:

`\"params\":\"{\\\"jobNumber\\\":\\\"0\\\"}\"`

Is this the expected behavior? That when you get the params the expectation is that it is a string that you need to decode separately? Rather than something like this:

`...,"params":{"jobNumber":0},...`

**Comment by gumbright** [comment]
This might have been premature, doing some more research.  Problem is at some point getting an encoding/decoding error and then the queue stops running.  I will reopen if needed.

**Comment by AugustAtSeattle** [comment]
My solution is saving an object as a string to pass.
