### ISSUE TITLE
What effect does changing the system clock have on the SwiftQueue scheduler?

### ISSUE THREAD

**Issue by robert-dodier** [lucas34/SwiftQueue#223]
I wonder if it's possible to say what is the expected effect of changing the system clock, when there is a job that is supposed to be executed on a fixed interval. 

A couple of possibilities that I can see when the clock jumps: maybe the job is just executed once, and then regularly thereafter, or maybe the job is executed multiple times, as many times as would have been executed in the interval over which the clock jumped. Or perhaps something else is going to happen. Is it possible to say a priori? Of course, I can carry out some experiments, but it would be nice if one could say ahead of time.

The context for this question is that I am contemplating changing the system clock in order to carry out some tests on an app, and I'm thinking about what the consequences of that would be. Thanks for any light you can shed on this question.

**Comment by lucas34** [comment]
I don't think changing the system time will make the job running sooner or later. Are you trying to change the system time for simulation and making the job running faster ?

**Comment by robert-dodier** [comment]
Hi, thanks for your reply. The particular application I have in mind is to test a system which has data being read at a fixed interval. For testing purposes, the sensor is disabled, and simulated data are generated. If the system just runs, without any clock changes, then 60/T data are generated each hour, where T is the sampling interval in minutes. Suppose that the clock is advanced an hour. Are 60/T values output all at once the next time the job is run? Or does the job continue to output values only every T actual minutes?

**Comment by lucas34** [comment]
I'm not sure, the best will be to test. I didn't test any scenario when changing system clock before. Do let me know what happen.
