### ISSUE TITLE
Exponential backoff with max delay

### ISSUE THREAD

**Issue by foxware00** [lucas34/SwiftQueue#226]
The `RetryConstraint` enum `exponential` case seems it will infinitely grow exponentially. 
My suggestion is to add an additional field for `maxDelay` such that.
`.exponential(initial: TimeInterval, maxDelay: TimeInterval)` to prevent it growing uncontrollably. Does this sound like something appropriate for this lib? Happy to construct a PR of you need some help.

```
let delay = info.currentRepetition == 1 ? initial : initial * pow(2, Double(info.currentRepetition - 1))
return min(maxDelay, delay)
```

**Comment by lucas34** [comment]
Sounds good to me ! Can you send a PR ?

**Comment by lucas34** [comment]
In my opinion it's better to go with the most straight forward solution. The solution 1 looks good to me

**Comment by lucas34** [comment]
Will be release in 3.1.1
