### ISSUE TITLE
BackgroundTasks from iOS 13

### ISSUE THREAD

**Issue by foxware00** [lucas34/SwiftQueue#249]
Is there any plans or ideas yet surrounding the BackgroundTasks API's release in iOS 13. I can see that allowing jobs to be scheduled to run when the app is backgrounded might be a very useful feature

**Comment by lucas34** [comment]
Hi, Thanks I was not aware of this API. I'll look into it. 
If you already know how to use it feel free to send open a pull request.

**Comment by lucas34** [comment]
BackgroundTask API support has been added. Please be aware that it's an experimental feature for now. I won't document it yet

**Comment by tomislav** [comment]
Would it possible to schedule a task to run only in the background? For example some maintenance tasks.

**Comment by lucas34** [comment]
@tomislav  It can be implemented. However right now it's for periodic job to keep running if the app goes in background.

**Comment by lucas34** [comment]
I'm not aware of the full limitation and capabilities of the API

**Comment by foxware00** [comment]
@lucas34 This looks great, I'll find some time to give it a play. Thanks for taking the time to look
