### ISSUE TITLE
Question: Is there a way to check if a job is in the queue?

### ISSUE THREAD

**Issue by hons82** [lucas34/SwiftQueue#264]
I'm using already the concurrency settings to ensure that only one job of a certain type is running.
What I'd need is to check if the job is already in the queue to show in the UI that there is no need to launch it again, but just wait for the job to finish

**Comment by lucas34** [comment]
Hi, 
JobBuilder.singleInstance() have 3 parameters. The latest one `includeExecutingJob` If set to true will also count the job that is current executing. 

So I suggest you schedule with 
```
.singleInstance(forId: "", override = false, includeExecutingJob = true)
```

If the current job is already running this new task will be rejected.

**Comment by hons82** [comment]
I'm using that already, and it's perfect.
However, in my use case I have a list of items that the user can download (serial, not parallel).
Once he clicks on an item I'm adding it to the queue so that it will be downloaded eventually.
Now in that UI I just wanna show that it is in the queue... so re-adding it is not a real option

**Comment by lucas34** [comment]
Got it. Right now it's not possible to check the queue prior scheduling event.
This could be added
