### ISSUE TITLE
How to listen when some job finished?

### ISSUE THREAD

**Issue by Tavernari** [lucas34/SwiftQueue#265]
Hi, 

I am trying to listen when some job finished, so I am using JobListener for it but when I try to read property from JobInfo it's appear internal property.. is it correct? How can I know what kind of job finished?

Can I set this properties public then send to PR?

Thanks in advance.

**Comment by lucas34** [comment]
That's a bug. Field should be public

**Comment by Tavernari** [comment]
https://github.com/lucas34/SwiftQueue/pull/266
