### ISSUE TITLE
start/stop queue

### ISSUE THREAD

**Issue by usamaj** [lucas34/SwiftQueue#284]
hey lucas hope you're doing well, i'm not sure how should i start or pause the queue using SwiftQueueManagerBuilder instance. I'm stuck on it, can you please help.

Sometimes when the app gets offline & become online after that the jobs doesn't start executing. Can you please tell what should i do when it is online again.

If i tried to build again using the builder it duplicates the current jobs

**Comment by lucas34** [comment]
Are you referring to the Network constraint that is not working properly ? Can you share the logs or having a sample project with the exact issue ?

**Comment by usamaj** [comment]
Yes it looks like a network constraint, jobs created in offline mode are not executing when device gets online.So is there a way to execute my created jobs or in other words start/stop the created queues when required.

Actually i couldn't found a way to start or stop queues except when creating SwiftQueueManagerBuilder singleton instance which automatically deserialises/executes all jobs on app start.

I just want to start/stop queues when required in app.

**Comment by lucas34** [comment]
What about using `SwiftQueueManager.isSuspended = true`
https://github.com/lucas34/SwiftQueue/blob/master/Sources/SwiftQueue/SwiftQueueManager.swift#L34

**Comment by usamaj** [comment]
yes it's doing the job for me...thanks for the help @lucas34
