### ISSUE TITLE
Job(Operation) Dependency/Chain

### ISSUE THREAD

**Issue by momoohidayat** [lucas34/SwiftQueue#286]
Is there any support for job/operation dependency or chained job?
maybe like this one:
https://developer.apple.com/documentation/foundation/operation/1416668-dependencies

one more thing, is there any support for chained input output from anothe job/operation?
maybe like this one:
https://www.avanderlee.com/swift/advanced-asynchronous-operations/

**Comment by lucas34** [comment]
There is no support for dependency so far and the chained input can be achieve by storing the data to a memory space that you can retrieve inside the following job
