### ISSUE TITLE
Offline job calls only once.

### ISSUE THREAD

**Issue by vavadiyahiren** [lucas34/SwiftQueue#290]
We have implemented swift queue to our project and used as i attached below and found some different behavior then expected. 

We used following technical stack to reproduce this behavior

Version 
Swift : 5.0
Switftqueue : 4.1.0
ReachabilitySwift (~> 5.0)

`struct QueueManagerBuilder {
    static let shared = SwiftQueueManagerBuilder(creator: QueueJobCreator()).set(persister: UserDefaultsPersister()).build()   
}`

`final class QueueManager: QueueManagerProtocol {    
    private var manager: SwiftQueueManager        
    init(withQueueManager manager: SwiftQueueManager = QueueManagerBuilder.shared) {
        self.manager = manager
    }
    
    func add(job: JobProtocol) {
        JobBuilder(type: job.jobType.value)
            .singleInstance(forId: getTimeStamp().description)
            .internet(atLeast: NetworkType.any)
            .with(params: job.params)
            .persist(required: true)
            .schedule(manager: self.manager)
    }
}`

When we add multiple job to queue while we are offline only one job get a call in onRun rest of the jobs are invoking on network available which could be a show stopper behavior.

I have printed a logs which i am attaching below.

> Internet: No Connection | mess- 123
> ChatMessageJob-onRun | Message: 123 | Internet: No Connection
> Internet: No Connection | mess- 456
> Internet: No Connection | mess- 789
> Internet: No Connection | mess- Abcd
> Internet: No Connection | mess- Xyzz
> Internet: No Connection | mess- Abcdd
> ChatMessageJob-onRun | Message: 456 | Internet: WiFi
> ChatMessageJob-onRun | Message: 789 | Internet: WiFi
> ChatMessageJob-onRun | Message: Abcd | Internet: WiFi
> ChatMessageJob-onRun | Message: Xyzz | Internet: WiFi
> ChatMessageJob-onRun | Message: Abcdd | Internet: WiFi

**Comment by lucas34** [comment]
If your job has no internet requirement or any, the constraint is not added to the job.
 
Is the issue only when the job has been deserialised ?

**Comment by vavadiyahiren** [comment]
I have tried removing the constraint but no luck.

I checked with the lib that if we need a persistent job we need to add JSON dictionary I guess and that is serialized string?

And surprisingly it works only once if you check the logs you might have better idea?

What else you need to help me out here more logs or code snippets?

**Comment by lucas34** [comment]
Can you setup the SwiftQueueManager with the option
`.set(logger: ConsoleLogger()) `

And send me the logs ?

**Comment by vavadiyahiren** [comment]
Hey @lucas34 ,

I think this was no longer a problem of the library I was adding a job with the same queue manager which was dependent on the internet so it was waiting for that job to get executed and finished.

After putting a log I get to know and fixed that and now it is working as expected.

Thanks for the help.

I am moving further and closing this ticket.
