### ISSUE TITLE
Add installation section

### ISSUE THREAD

**Issue by lfarah** [lucas34/SwiftQueue#3]
Hey @lucas34 , your lib is awesome but your README lacks an installation section
I created this [iOS README template](https://github.com/awesome-labs/iOS-readme-template) to help you out 😉 

Please fix this issue before we can approve [the AwesomeiOS PR](https://github.com/vsouza/awesome-ios/pull/1924)

**Comment by lucas34** [comment]
Thanks for the template. I updated the readme to make it more clear.

**Comment by lucas34** [comment]
Revise of ReadMe and wiki done. Let me know if you see any missing piece in the documentation. Jazzy doc will come soon.
