### ISSUE TITLE
Has periodic been tested with SwiftUI?

### ISSUE THREAD

**Issue by ApostolisApo** [lucas34/SwiftQueue#305]
I am creating the following job 

`
            JobBuilder(type: NotificationJob.type)
                .delay(time: 10)
                .periodic(limit: .limited(20), interval: 10)
                .persist(required: true)
                .retry(limit: .limited(5))
                .schedule(manager: self.manager)
`

but it only runs once and then never until the job is created again. Can it be that it is a SwiftUI app? 
The job itself is like this: 

`class NotificationJob: Job {
    
    static let type = "NotificationJob"
    
    func onRun(callback: JobResult) {
        print("job running")
        let userNotificationCenter = UNUserNotificationCenter.current()
        let notificationContent = UNMutableNotificationContent()

        // Add the content to the notification content
        notificationContent.title = "Notification. \(Date().timeIntervalSince1970)"
        notificationContent.body = "Notification. \(Date().timeIntervalSince1970)!"
        notificationContent.badge = NSNumber(value: 1)

        let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 5,
        repeats: false)
        let request = UNNotificationRequest(identifier: UUID().uuidString,
        content: notificationContent,
        trigger: trigger)
        userNotificationCenter.add(request) { (error) in
            if let error = error {
                print("Notification Error: ", error)
            }
        }
    }

    func onRetry(error: Error) -> RetryConstraint {
        print("error while running job")
        return .retry(delay: 10)
    }

    func onRemove(result: JobCompletion) {
        print("removing job")
        // This job will never run anymore
        switch result {
            case .success:
                // Job success
            break
            
            case .fail(let error):
                // Job fail
            break
       
        }
    }
}
`

and the job creator:

`
class NotificationJobCreator: JobCreator {
    
    // Base on type, return the actual job implementation
    func create(type: String, params: [String: Any]?) -> Job {
        // check for job and params type
        if type == NotificationJob.type  {
            return NotificationJob()
        } else {
            // Nothing match
            // You can use `fatalError` or create an empty job to report this issue.
            fatalError("No Job !")
        }
    }
}`

**Comment by lucas34** [comment]
The library should not have anything to do with SwiftUI. 1 thing 
Can you enable the internal logger and dump the logs here ?

**Comment by gharary** [comment]
I have the same issue with version 5, Swift 5, Xcode 12.5.
It just run once.

**Comment by onlymate** [comment]
Hi! This happens if you don't call the callback in your "onRun" function
