### ISSUE TITLE
Understanding how to run SwiftQueue jobs in the background

### ISSUE THREAD

**Issue by momentsdesigns** [lucas34/SwiftQueue#339]
It appears that SwiftQueue has support for the `BackgroundTask` framework, but doesn't include much documentation as to how it should be used.

Here's what I've figured out so far – could you help fill in the rest?

1. In `application:didFinishLaunching`, I register a task identifier:

```swift
let taskIdentifier = "com.myapp.uploadJobTask"
queueManager.registerForBackgroundTask(forTaskWithUUID: taskIdentifier)
```

2. I included `"com.myapp.uploadJobTask"` in my `Info.plist` under `BGTaskSchedulerPermittedIdentifiers`.

3. Use the following `JobBuilder` (note that `.parallel` is used to name the queue the same as the task identifier:

```swift
JobBuilder(type: UploadPhotoJob.type)
    // One job per upload
    .singleInstance(forId: String(photo.id))
   
    // Name the queue so SwiftQueue create a background task
    .parallel(queueName: "com.myapp.uploadJobTask")

    .with(params: [
        ...
    ]).retry(limit: .limited(5))
    
    .persist(required: true)
    
    .schedule(manager: queueManager)
```

**Here's where I'm not sure:**

4. When the app goes into the background, call:

```swift
queueManager.applicationDidEnterBackground()
```

However, this eventually calls `getAllAllowBackgroundOperation()`, which filters the jobs by their `executor` value (which defaults to `.foreground`).

It looks like the only way of setting the job to `.background` or `.any` is to use `.periodic`, which doesn't make sense for an upload job. 

What is the correct way of specifying that the job can/should be executed in either foreground or background?

Furthermore, are there any other steps required to support background task execution?

Thank you!

**Comment by momentsdesigns** [comment]
One follow-up issue:

In SwiftQueue's `scheduleBackgroundTask` function:

```swift
func scheduleBackgroundTask() {
        let request = BGProcessingTaskRequest(identifier: info.uuid)
        ...
}
```

`info.uuid` is used for the background task. However, in this case, the job's `uuid` is the `.singleInstance` id, which is dynamic (could be `1`, `52`, whatever).

It looks likes the `identifier` needs to be the identifier listed in `Info.plist`, in this case, `com.myapp.photoUploadJob`, not a dynamic `uuid`.

So, how can I both use `.singleInstance` **and** create a background task request, given that `info.uuid` will never match what's in the permitted identifiers in `Info.plist`?

Thank you!

**Comment by lucas34** [comment]
Why not using

```swift
singleInstance(forId: "com.myapp.photoUploadJob")
```

info.uuid will then be this id.

**Comment by lucas34** [comment]
Oh it looks like you want en entire queue to run in background. That was not designed that way. I was thinking to have a repeated job (For synchronisation or something) that need to run every X minutes and ca be run in background.

Your requirement looks much more complex than the current implemented solution

**Comment by BenJHowell** [comment]
For a Job to be executed / called from within a BGTask, does just the SwiftQueueManager need to be referenced (to be in memory) and given enough Time to execute persisted Jobs which already in the queue?

**Comment by CinGiu** [comment]
Did you guys find a solution or an alternative? @BenJHowell @vishnukaey

**Comment by PranayDVigo** [comment]
@CinGiu Did you guys find a solution or an alternative?
