### ISSUE TITLE
Carthage build only builds dependencies

### ISSUE THREAD

**Issue by peterBodybarista** [lucas34/SwiftQueue#350]
With the update to Xcode12 I hade to use their fix to being able to build the carthage. But all my attempts only downloads SwiftQueue and only builds the dependency **Reachability.xcodeproj**

```
... % ./carthage.sh build SwiftQueue --platform iOS
*** xcodebuild output can be found in /var/folders/t4/15_cn1116cnbvwbsp0npwgn40000gn/T/carthage-xcodebuild.tc4G9D.log
*** Downloading SwiftQueue.framework binary at "4.3.0"
*** Building scheme "Reachability" in Reachability.xcodeproj
... % 
```
Am I doing anything wrong and how do I get the carthage to build the scheme of "SwiftQueue" as it has previously done for Xcode11?

**Comment by lucas34** [comment]
I have the same issue

**Comment by lucas34** [comment]
Issue is on carthage side. They don't support Xcode 12 yet. I'm also downgrading the CI to use Xcode 11
