### ISSUE TITLE
jobManager.cancelAllOperations() not cancelling unlimited periodic jobs

### ISSUE THREAD

**Issue by PJS28** [lucas34/SwiftQueue#355]
I have added a job to the global job manager instance, following is the code snippet from my project. And after log out, I'm calling Current.jobManager().cancelAllOperations() but still this periodic jobs continues to run even after calling the "cancelAllOperations".  Am I missing something here, please help me out?

            JobBuilder(type: "REFRESH")
                .singleInstance(forId: "REFRESH_\(pinId)")
                .priority(priority: .normal)
                .internet(atLeast: .cellular)
                .with(params: params)
                .delay(time: TimeInterval.init(refreshInterval))
                .periodic(limit: .unlimited, interval: TimeInterval.init(refreshInterval))
                .schedule(manager: Current.jobManager())

**Comment by lucas34** [comment]
That's a bug. The re-schedule is not checking if the job is canceled 😱

**Comment by lucas34** [comment]
I can't reproduce the issue. I'm adding test case for this specific test
