### ISSUE TITLE
Pending work not excuted when app run again

### ISSUE THREAD

**Issue by Mactacs** [lucas34/SwiftQueue#360]
Hi. I'm impressed with this library but I'm having a bit of confusion about why my work doesn't execute when my app relaunches again. This is the scenario. I have a button that will create work. When I click the button (mobile data or wifi enabled), It will create new work and successfully execute work. Now when I turn off the mobile data and wifi and click the button again and close and relaunches the app. The work doesn't execute. Unlike in the android work manager, works in the queue will execute even the app was killed. Below is my code : 

SwiftUI Button :
`Button(action: {
                let manager = SwiftQueueManagerBuilder(creator: ApplicationJobCreator()).build()
                JobBuilder(type: AttendanceWorker.type)
                        .internet(atLeast: .cellular)
                        .with(params: ["content": "Hello world"])
                        .schedule(manager: manager)
            }) {
                HStack(spacing:10) {
                    Image(systemName : "escape")
                        .resizable()
                        .renderingMode(.template)
                        .frame(width: 24, height: 24)
                        .foregroundColor(.gray)
                    Text("Logout")
                        .foregroundColor(Color.black)
                    Spacer()
                }
            }
            .padding(.horizontal,7)
            .padding(.vertical,7)
            .background(Color.clear)
            .cornerRadius(10)`

WorkManager Class: 
`
import Foundation
import SwiftQueue
import Alamofire

class AttendanceWorker :  Job {
    
    static let type = "AttendanceWorker"
    
    func onRun(callback: JobResult) {
        let attendanceRepository = AttendanceRepository()
        attendanceRepository.uploadPendingAttendance() { response in
            if response == 1 {
                callback.done(.success)
            } else {
                callback.done(.fail(ApiError.fail))
            }
        }
    }
    
    func onRetry(error: Error) -> RetryConstraint {
//        return error is .error ? RetryConstraint.cancel : RetryConstraint.retry(delay: 0)
        return RetryConstraint.retry(delay: 0)
    }
    
    func onRemove(result: JobCompletion) {
        switch result {
        case .success:
            print("JOB SUCCESS")
            break
        case .fail(let error) :
            print("JOB FAILED with an error : \(error)")
            break
        }
    }
    
    
}

class ApplicationJobCreator: JobCreator {
    func create(type: String, params: [String : Any]?) -> Job {
        if type == AttendanceWorker.type {
            return AttendanceWorker()
        } else {
            fatalError("No Job!")
        }
    }
}
`

AttendanceRepository.swift:
`
import Foundation
import Alamofire

struct AttendanceRepository {
    
    private var networkService : NetworkService
    
    init(networkService : NetworkService = NetworkService()) {
        self.networkService = networkService
    }
}

extension AttendanceRepository {
    
    func uploadPendingAttendance(completion:@escaping(Int) -> Void) {
        print("UPLOAD PENDING ATTENDANCE!!!! ")
    }
}
`

**Comment by Narayane** [comment]
@Mactacs 
you have forgotten to call `.persist` to allow this mechanism when you use `JobBuilder`...

**Comment by Mactacs** [comment]
@Narayane I already added persist to my JobBuilder but it doesn't solve the issue.
