### ISSUE TITLE
Migration from 4.x to 5.x

### ISSUE THREAD

**Issue by Narayane** [lucas34/SwiftQueue#361]
Hi,

You have mentionned in v5.0 changelog:

```
Warning: This version is incompatible with 4.X
If you are using serialised task. After updating, the library will not be able to deserialised the task saved with version 4.X
```

Any app crash risk if it was the case?
Are 4.X persisted jobs "removed" from UserDefaults by v5.0 before persist its own jobs?

Thanks

**Comment by lucas34** [comment]
After migrating to the version 5, the new lib will not be able to deserialise the previous job, So the job will not be restored. It will not crash and you will see a log.

What I suggest is to delete the file that contains all the jobs, or using another file name. If you are using UserDefaultsPersister, you can specify the file name as parameter.
It's up to each developer on how to handle the cases where the jobs are lost.
