### ISSUE TITLE
Persisted jobs are not removed anymore in v5.0

### ISSUE THREAD

**Issue by Narayane** [lucas34/SwiftQueue#362]
Hi,

I notice a bug between v4.3 and v5.0. My persisted jobs are not removed anymore from `UserDefaults`.
I have a `JobPersister` custom implementation which is the same than your `UserDefaultsPersister` but with logs.

I have 3 test cases to validate my jobs work:

1. full online // nominal case
2. offline then online without app kill // test connectivity return
3. offline, app kill, online, app launch, run the persisted jobs, app kill, app relaunch // test persistence

With v5.0, 1. and 2. are ok but 3. fails. I used the same process in both cases below.

**App launch logs with SwiftQueue v4.3**: "witness" logs

16:59:29.180 💜 VERBOSE LRJobPersister.init():19 - create a LR job persister
16:59:29.183 💜 VERBOSE LRJobPersister.restore():26 - restore
16:59:29.183 💜 VERBOSE LRJobPersister.restore():34 - restore in queue
16:59:29.183 💚 DEBUG AutoRenameRideJob.init():64 - create a job to auto rename ride 2
16:59:29.184 💚 DEBUG ResumeRideJob.init():66 - create a job to resume ride 2
16:59:29.185 💚 DEBUG PauseRideJob.init():65 - create a job to pause ride 2
16:59:29.186 💚 DEBUG StartRideJob.init():103 - create a job to start ride 2
16:59:29.187 💜 VERBOSE LRJobPersister.put():42 - insert in queue
16:59:29.189 💜 VERBOSE LRJobPersister.put():42 - insert in queue
16:59:29.189 💚 DEBUG StartRideJob.onRun():110 - run the job to start ride 2
16:59:29.189 💜 VERBOSE LRJobPersister.put():42 - insert in queue
16:59:29.190 💜 VERBOSE LRJobPersister.put():42 - insert in queue
16:59:29.670 💚 DEBUG StopRideJob.init():88 - create a job to stop ride 2
16:59:29.671 💜 VERBOSE LRJobPersister.put():42 - insert in queue
16:59:30.408 💜 VERBOSE LRJobPersister.remove():54 - remove from queue
16:59:30.408 💚 DEBUG PauseRideJob.onRun():72 - run a job to pause ride 2
16:59:30.410 💚 DEBUG StartRideJob.onRemove():144 - remove the job to start ride 2
16:59:30.410 💙 INFO StartRideJob.onRemove():150 - ride 2 has been started
16:59:30.518 💜 VERBOSE LRJobPersister.remove():54 - remove from queue
16:59:30.518 💚 DEBUG ResumeRideJob.onRun():73 - run a job to resume ride 2
16:59:30.520 💚 DEBUG PauseRideJob.onRemove():108 - remove a job to pause ride 2
16:59:30.520 💙 INFO PauseRideJob.onRemove():114 - ride 2 is paused
16:59:30.821 💜 VERBOSE LRJobPersister.remove():54 - remove from queue
16:59:30.822 💚 DEBUG AutoRenameRideJob.onRun():72 - run a job to auto rename ride 2
16:59:30.823 💚 DEBUG ResumeRideJob.onRemove():109 - remove a job to resume ride 2
16:59:30.823 💙 INFO ResumeRideJob.onRemove():115 - ride 2 is resumed
16:59:31.215 💜 VERBOSE LRJobPersister.remove():54 - remove from queue
16:59:31.215 💚 DEBUG StopRideJob.onRun():96 - run the job to stop ride 2
16:59:31.218 💚 DEBUG AutoRenameRideJob.onRemove():119 - remove the job to auto rename ride 2
16:59:31.219 💙 INFO AutoRenameRideJob.onRemove():125 - ride 2 has been auto renamed
16:59:31.414 💜 VERBOSE LRJobPersister.remove():54 - remove from queue
16:59:31.416 💚 DEBUG StopRideJob.onRemove():130 - remove the job to stop ride 2
16:59:31.416 💙 INFO StopRideJob.onRemove():136 - ride 2 has been stopped

**App launch logs with SwiftQueue v5.0**: No prints of _insert in queue_, 4 prints of _restore in queue_ for persisted jobs and only one print of _remove from queue_ for StopRideJob which is the only one not persisted. Persisted jobs are restored, curiously not inserted and not removed

16:24:13.940 💜 VERBOSE LRJobPersister.init():17 - create a LR job persister v5
16:24:13.940 💜 VERBOSE LRJobPersister.restore():26 - restore
**16:24:13.940 💜 VERBOSE LRJobPersister.restore():34 - restore in queue
16:24:13.940 💜 VERBOSE LRJobPersister.restore():34 - restore in queue
16:24:13.941 💜 VERBOSE LRJobPersister.restore():34 - restore in queue**
16:24:13.942 💚 DEBUG AutoRenameRideJob.init():64 - create a job to auto rename ride 1
16:24:13.944 💚 DEBUG ResumeRideJob.init():66 - create a job to resume ride 1
16:24:13.946 💚 DEBUG StartRideJob.init():103 - create a job to start ride 1
16:24:13.947 💚 DEBUG PauseRideJob.init():65 - create a job to pause ride 1
**16:24:13.947 💜 VERBOSE LRJobPersister.restore():34 - restore in queue**
16:24:13.950 💚 DEBUG StartRideJob.onRun():110 - run the job to start ride 1
16:24:15.139 💚 DEBUG StartRideJob.onRemove():144 - remove the job to start ride 1
16:24:15.140 💙 INFO StartRideJob.onRemove():150 - ride 1 has been started
16:24:15.140 💚 DEBUG PauseRideJob.onRun():72 - run a job to pause ride 1
16:24:15.469 💚 DEBUG PauseRideJob.onRemove():108 - remove a job to pause ride 1
16:24:15.471 💙 INFO PauseRideJob.onRemove():114 - ride 1 is paused
16:24:15.477 💚 DEBUG ResumeRideJob.onRun():73 - run a job to resume ride 1
16:24:15.645 💚 DEBUG AutoRenameRideJob.onRun():72 - run a job to auto rename ride 1
16:24:15.645 💚 DEBUG ResumeRideJob.onRemove():109 - remove a job to resume ride 1
16:24:15.645 💙 INFO ResumeRideJob.onRemove():115 - ride 1 is resumed
16:24:15.983 💚 DEBUG AutoRenameRideJob.onRemove():119 - remove the job to auto rename ride 1
16:24:15.985 💙 INFO AutoRenameRideJob.onRemove():125 - ride 1 has been auto renamed
**16:24:14.774 💚 DEBUG StopRideJob.init():88 - create a job to stop ride 1
16:24:14.774 💜 VERBOSE LRJobPersister.put():42 - insert in queue**
16:24:15.983 💚 DEBUG AutoRenameRideJob.onRemove():119 - remove the job to auto rename ride 1
16:24:15.985 💙 INFO AutoRenameRideJob.onRemove():125 - ride 1 has been auto renamed
**16:24:15.986 💚 DEBUG StopRideJob.onRun():96 - run the job to stop ride 1
16:24:16.150 💜 VERBOSE LRJobPersister.remove():54 - remove from queue
16:24:16.151 💚 DEBUG StopRideJob.onRemove():130 - remove the job to stop ride 1
16:24:16.153 💙 INFO StopRideJob.onRemove():136 - ride 1 has been stopped**

**Comment by Narayane** [comment]
@lucas34?

**Comment by lucas34** [comment]
So the job is restored but never run ?

**Comment by lucas34** [comment]
I have test cases for this so I'm trying to understand, are you able to reproduce with test cases ?

**Comment by Narayane** [comment]
Persisted jobs are restored, run but no more removed from persistence. At next app launchs, persisted jobs will be restored again and again.
In my previous logs with v5.0, only StopRideJob is correctly removed because it is the only one which has not be persisted.

**Comment by lucas34** [comment]
@Narayane  Looks like it's because DefaultConstraintMaker doesn't re-add the persister constraint.

**Comment by lucas34** [comment]
Will be part of 5.0.1

**Comment by Narayane** [comment]
Thank you @lucas34

**Comment by Narayane** [comment]
Hi @lucas34,

I have just tested v5.0.1 and I'm sorry but bug is still present... Persisted jobs are not removed from "persistence" if app has been killed. There are still restored again and again... 😕

**Comment by Narayane** [comment]
@lucas34?
