### ISSUE TITLE
Possibility of running N concurrent jobs inside a queue

### ISSUE THREAD

**Issue by cristianilea-lateral** [lucas34/SwiftQueue#377]
So from what I understand, I can only create one queue which runs each job sequentially OR create multiple queues to run jobs in parallel.

I would like to create a scenario where I limit the number of active jobs to about 5, run them in parallel, but when one finishes, start a new job from the queue.

Is there a simple way of achieving that?

**Comment by lucas34** [comment]
Right now not really, the SwiftQueue was designed to run jobs in queue (One by one), but allowing multiple queues. Your problem here looks closer to an execution pool than an actual queue use case.

**Comment by BenJHowell** [comment]
@cristianilea-lateral maybe you can create one "meta queue" which takes care of the "sub"-queues utilising kind of a round robin system. i have implemented a quasi round robin system to always keep only a limited number of jobs executed in parallel. 
@lucas34 Could be an extension in the future maybe? great work by the way!
