### ISSUE TITLE
Periodic run just once

### ISSUE THREAD

**Issue by gharary** [lucas34/SwiftQueue#381]
I have the same issue as #305 and the periodic job run once only.
never again.

SwiftQeueu 5, Swift UI, Xcode 12.5

**Comment by lucas34** [comment]
Hi, Thanks for reporting, Please Either
- Provide test case to reproduce
- Write Unit test with reproducible issue 

Closing as not enough informations

**Comment by onlymate** [comment]
Hi! This happens if you don't call the callback in your "onRun" function
