### ISSUE TITLE
EXC_BAD_ACCESS in the method createQueue

### ISSUE THREAD

**Issue by ra1popov** [lucas34/SwiftQueue#388]
Hello,
Thanks for your work.

I have a problem while using your library SwiftQueue (5.0.2).
I modified your example and added .parallel (queueName: job.queueName) to QueueManager. See attach TestSwiftQueue.zip

I get the error "Thread 11: EXC_BAD_ACCESS (code=1, address=0x18)" in the method createQueue (SwiftQueueManager.swift). At the first start of the application, everything seems to work fine. But i get an error if restart the app.

let job = FindDeviceJob(id: i, queue: "queue_\\(i / 25)")       // it doesn't work
let job = FindDeviceJob(id: i, queue: "queue")                     // same error, but it occurs less often

The error appears very often on an emulator and very rarely on a real device..

I use Xcode 12.5. Can you tell me what could be the problem?

I think the problem is that the class member "manage" is being accessed from different threads.

[TestSwiftQueue.zip](https://github.com/lucas34/SwiftQueue/files/6614483/TestSwiftQueue.zip)

<img width="1431" alt="exc_bad_access" src="https://user-images.githubusercontent.com/70153758/121144555-62708180-c83e-11eb-8f0e-00fc6672eb74.png">

<img width="1431" alt="thread_kill" src="https://user-images.githubusercontent.com/70153758/121148712-4f5fb080-c842-11eb-8a94-897f70107ae1.png">

**Comment by ra1popov** [comment]
I think I solved the problem. I think I solved the problem. I think the problem is access to "manage" dictionary from different threads. I added a sync method and it worked now.

Code example:

    private let locker = NSCondition()
    
    func synchronized(closure:() -> (SqOperationQueue)) -> SqOperationQueue {
        locker.lock()
        defer {
            locker.unlock()
        }
        return closure()
    }

and fixed "getQueue" and "createQueue" methods:

internal func getQueue(queueName: String) -> SqOperationQueue {
        synchronized {
            if (manage[queueName] == nil) {
                manage[queueName] = SqOperationQueue(params, params.queueCreator.create(queueName: queueName), false)
            }
            return manage[queueName]!
        }
    }

    private func createQueue(queueName: String, initInBackground: Bool) -> SqOperationQueue {
        synchronized {
            let operationQueue = SqOperationQueue(params, params.queueCreator.create(queueName: queueName), isSuspended)
            manage[queueName] = operationQueue
            return operationQueue
        }
    }

**Comment by lucas34** [comment]
Interesting, Anything I can add in the lib to cover this use case ?

**Comment by ra1popov** [comment]
I think need to fix the file SwiftQueueManager.swift

1. Add this code
private let locker = NSCondition()
    
    func synchronized(closure:() -> (SqOperationQueue)) -> SqOperationQueue {
        locker.lock()
        defer {
            locker.unlock()
        }
        return closure()
    }

2. And replace getQueue and createQueue methods to

    internal func getQueue(queueName: String) -> SqOperationQueue {
        synchronized {
            if (manage[queueName] == nil) {
                manage[queueName] = SqOperationQueue(params, params.queueCreator.create(queueName: queueName), false)
            }
            return manage[queueName]!
        }
    }

    private func createQueue(queueName: String, initInBackground: Bool) -> SqOperationQueue {
        synchronized {
            let operationQueue = SqOperationQueue(params, params.queueCreator.create(queueName: queueName), isSuspended)
            manage[queueName] = operationQueue
            return operationQueue
        }
    }

it's all.
