### ISSUE TITLE
Not able to access registerForBackgroundTask method in SwiftQueueManager+BackgroundTask

### ISSUE THREAD

**Issue by kumararvind** [lucas34/SwiftQueue#390]
let taskIdentifierSite = "com.abc.BGProcessingIdentifier"
     queueManager = SwiftQueueManagerBuilder(creator: SJobCreator()).set(logger: ConsoleLogger()).build()

     queueManager?.registerForBackgroundTask(forTaskWithUUID: taskIdentifierSite)

Getting Error : "Value of type 'SwiftQueueManager' has no member 'registerForBackgroundTask'"

**Comment by lucas34** [comment]
Can you reproduce in unit test ?
