### ISSUE TITLE
Start / Stop queue

### ISSUE THREAD

**Issue by lucas34** [lucas34/SwiftQueue#4]
Create a function to start or pause execution. Will makes testing easier.

**Comment by usamaj** [comment]
hey lucas hope you're doing well, i'm not sure how should i start or pause the queue using SwiftQueueManagerBuilder instance. I'm stuck on it, can you please help.

Sometimes when the app gets offline & become online after that the jobs doesn't start executing. Can you please tell what should i do when it is online again
