### ISSUE TITLE
Replace Reachability dependency with NWPathMonitor usage

### ISSUE THREAD

**Issue by GianniCarlo** [lucas34/SwiftQueue#406]
Hi, I've been looking into integrating this library into my project, with the purpose of using it across iOS and watchOS. Xcode won't build the watchOS target due to the Reachability dependency, which uses `SystemConfiguration` as stated in #379 (no matter if I use anything related to reachability or not, just including it in my watchOS target fails to compile) 

<img width="871" alt="Screen Shot 2022-06-21 at 08 41 23" src="https://user-images.githubusercontent.com/14112819/174813920-35c5486a-f992-4260-b312-2b18702eff50.png">

Would you be interested in a PR replacing the use of Reachability for [NWPathMonitor](https://developer.apple.com/documentation/network/nwpathmonitor) from the [Network framework](https://developer.apple.com/documentation/network) which is available on all platforms (although the targets are higher: iOS 12+, macOS 10.14+, watchOS 5.0+, etc)?

I saw [one article from Hacking with Swift](https://www.hackingwithswift.com/example-code/networking/how-to-check-for-internet-connectivity-using-nwpathmonitor) and the usage looks pretty straight forward, and it also makes available the `isExpensive` flag for connections

**Comment by lucas34** [comment]
Sure I have been looking at dropping reachability.
Feel free to send a Pull Request

**Comment by lucas34** [comment]
@GianniCarlo I have merged it. Thanks for your contribution. 
I'll make additional testing and will release a new version. Probably 6.0

**Comment by GianniCarlo** [comment]
Awesome! let me know if I can be of any help 👍

**Comment by lucas34** [comment]
@GianniCarlo 6.0.0 is released. Let me know if everything works fine.
Appreciate your contribution.
