### ISSUE TITLE
Get additional info for a job

### ISSUE THREAD

**Issue by ivan-kolesov** [lucas34/SwiftQueue#409]
Is it possible to get additional information about a running task: scheduled start time, number of iterations, task status (pending, running, completed)? If it were possible to obtain an instance of SqOperation publicly, then this question would not exist.

**Comment by lucas34** [comment]
You can use JobListener and react based on different events

**Comment by ivan-kolesov** [comment]
> You can use JobListener and react based on different events

Tried to play with JobListener, but can't get nextRunSchedule that handles SqOperation only.

**Comment by lucas34** [comment]
What does nextRunSchedule means ?

**Comment by ivan-kolesov** [comment]
> nextRunSchedule
This means when the next time job will start based on scheduled time. Because retry delay might be linear or exponential and no any way to determine the delay inside a job.

**Comment by ivan-kolesov** [comment]
> 

Thanks, I want to see the info not in internal logger, but  somewhere as you offered, in JobListener.
If I implement a custom constraint will the constraint persist in the storage where job saves?

**Comment by lucas34** [comment]
Yes if your custom constraint extends CodableConstraint.
Also you will need a custom ConstraintMaker to re-add the custom constraint when deserialiser.

All internal constraints Are also created using this mechanism

**Comment by ivan-kolesov** [comment]
Retry Constraint is marked as final, and it's not a good idea cloning the constraint for modifying a few lines
