### ISSUE TITLE
Multiple Parallel Periodic jobs do not run in parallel

### ISSUE THREAD

**Issue by saltyskip** [lucas34/SwiftQueue#434]
Im trying to trigger multiple periodic jobs so that both of them run simultaneously in parallel in the same queue.
```
  JobBuilder(type: SyncBTCRateJob.type)
      .periodic(limit: .limited(2), interval: 5)
      .parallel(queueName: "sameQ")
      .schedule(manager: TasksScheduler.shared.backgroundJobQueue)
  JobBuilder(type: SyncFiatRatesJob.type)
      .periodic(limit: .limited(2), interval: 5)
      .parallel(queueName: "sameQ")
      .schedule(manager: TasksScheduler.shared.backgroundJobQueue) 
  ```
  
  **Expected Behavior**
  In the above I expect that SyncBTCRate and SyncFiatRates will run in parallel every 5 seconds twice, and both are removed from the queue at roughly the same time, completing in roughly 10 seconds
  
**Observed Behavior**
  SyncBTCrate runs twice at a 5 second interval and then SyncFiatRates runs twice at a 5 second interval so the total process takes about 20 seconds.
  
  The outputted logs are as follows  
<img width="356" alt="image" src="https://user-images.githubusercontent.com/14796429/224894893-24c337e4-f657-49a7-a831-77a459ccdaa3.png">

Is it possible to trigger multiple periodic jobs concurrently or is this the expected behavior

**Comment by lucas34** [comment]
parallel was designed to run on different queue. What's the use case to run in parallel in the same queue  ?

**Comment by saltyskip** [comment]
I see it seems I misread the documentation as parallel is requiring different queues for the jobs to run in parallel. Thank you!
