### ISSUE TITLE
Investigating a Zombie Object Crash from operation.run()

### ISSUE THREAD

**Issue by Kenpaypay** [lucas34/SwiftQueue#441]
I'm currently tracking down a zombie object crash in which we get a `EXC_BAD_ACCESS KERN_INVALID_ADDRESS ` crash in SQOperation.swift for whenever super.cancel() is called in cancel() for SQOperation.swift. We see this happening on the run closures in Constraint+deadline.swift, Constraint+retry.swift, Constraint+network.swift. Something that I have noticed is that we sometimes strongly capture operation and sometimes we capture operation weakly. I'm curious on why we have mixed capturing of the operation variable.  See below for an example: 
**Operations**
<img width="725" alt="Screenshot 2024-08-30 at 4 41 20 PM" src="https://github.com/user-attachments/assets/d7a97d8e-bb49-4c1d-90b5-ba05306148ef">

**Constaint+network.swift**

<img width="780" alt="Screenshot 2024-08-30 at 5 15 47 PM" src="https://github.com/user-attachments/assets/a5b0067a-2888-4ea1-a48f-2b58960218d8">

**Comment by lucas34** [comment]
Can you create a PR ?

**Comment by Kenpaypay** [comment]
Thank you for responding @lucas34, let me do some preliminary testing and I will raise a PR 🙇
