### ISSUE TITLE
Crashing in JobBuilder create with custom params

### ISSUE THREAD

**Issue by aasatt** [lucas34/SwiftQueue#60]
Im getting a crash on the `assert` in this function in the `JobBuilder` class.

```
    /// Custom parameters will be forwarded to create method
    public func with(params: [String: Any]) -> Self {
        assert(JSONSerialization.isValidJSONObject(params))
        info.params = params
        return self
    }
```

Before moving to the new code I was passing things like delegates and callbacks to my job but since those are not valid JSON but conform to `Any` it crashes on this assertion. 

I'm not sure if this is intended or not but it does mention "Validate JSON argument" int the 1.4.0 change log so maybe. If it was intended, is there a better way to get callback blocks and updates from a job?

**Comment by lucas34** [comment]
Hi,
The params will be converted to string JSON when serialising the task. However, I should only validate this if you persist the task. I will update this.

**Comment by lucas34** [comment]
Will be release in 1.4.1
