### ISSUE TITLE
"-1" won't run the job indefinitely

### ISSUE THREAD

**Issue by moyoteg** [lucas34/SwiftQueue#79]
`            .periodic(count: -1, interval: 5*60)
`
won't run the job indefinitely 

I am having to do:
`            .periodic(count: 9999, interval: 5*60)
`

**Comment by moyoteg** [comment]
I am using version `SwiftQueue (1.3.0)`

**Comment by moyoteg** [comment]
my pod file now looks like: `pod 'SwiftQueue', :git => 'https://github.com/lucas34/SwiftQueue.git'` and I have the latest version =).

**Comment by lucas34** [comment]
Last version should be 1.5.0 
[https://cocoapods.org/pods/SwiftQueue](https://cocoapods.org/pods/SwiftQueue)

Maybe you can try `pod repo update` or `pod update`
