### ISSUE TITLE
What happens with job on "applicationDidEnterBackground"

### ISSUE THREAD

**Issue by moyoteg** [lucas34/SwiftQueue#81]
if the application enters :
```swift 
applicationDidEnterBackground(_:)
```
would a job persist once it comes back to the foreground?

**Comment by lucas34** [comment]
As long as the app stays in memory, All the jobs will stay as well.
Persisted Job is only when you kill the app, once you restart, you may want to retrieve those pending jobs.

**Comment by afterthought** [comment]
Take this for what it's worth, but I figured I would chime in with how I coded this in an app that uses SwiftQueue. Thanks btw, @lucas34... My queues are running API GET/POST operations in the background and I wanted to ensure that anything inflight was finished (didn't seem to make sense to use apple's NSURLSession background support here)... I know this won't be super easy to follow without seeing the rest of the app code, but the basic objective is to ensure that any inflight API calls can complete and that the state of the application can be updated/persisted with the results before the app gets frozen. Maybe this will help someone else someday.

    func applicationDidEnterBackground(_ application: UIApplication) {
        taskId = application.beginBackgroundTask(withName: "StopJobs", expirationHandler: {
            application.endBackgroundTask(self.taskId)
        })

        if taskId != UIBackgroundTaskInvalid {
            DispatchQueue.global(qos: .background).async {
                os_log("Temporarily pause ALL swiftqueue jobs while we drain NETWORK operationQueue")
                queueManager.pause()
                self.drainNetworkOperations()

                os_log("Set to background state - triggers Post/fetch job cancellation")
                OperationQueue.main.addOperation {
                    store.dispatch(SetBackgroundState(appInBackground: true))
                }
                os_log("Restart swiftqueue jobs. Post/fetch jobs are still cancelled now.")
                queueManager.start()
                os_log("Drain MAIN operationQueue, to ensure all work items are finished.")
                self.drainActiveJobMainOperations()

                os_log("Drain JobQueues.")
                queueManager.waitUntilAllOperationsAreFinished()

                application.endBackgroundTask(self.taskId)
            }

        }

    }
